
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/expensesdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
